### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "mail1@gmail.com",
    "password": "pass"
}

### Sign out
POST http://localhost:3000/auth/signout

### Get current user loged in
GET http://localhost:3000/auth/whoami

### Find user with id
GET http://localhost:3000/auth/2

### Find all users with email
GET http://localhost:3000/auth?email=mail@gmail.com

### Delete user with id
DELETE http://localhost:3000/auth/1

### Update user with id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "mail@gmail.com"
}

